from datetime import UTC, datetime

from app.schemas import Equipment, Place


FETCHED_AT = datetime(2026, 6, 23, 14, 0, tzinfo=UTC)


def equipment(
    *,
    id: str,
    equipment_type: str,
    name: str,
    evidence: str,
    source: str,
    confidence: float,
    model: str | None = None,
    width: float | None = None,
    length: float | None = None,
    materials: list[str] | None = None,
    formats: list[str] | None = None,
    training: bool | None = None,
    staff_assisted: bool | None = None,
    self_service: bool | None = None,
) -> Equipment:
    """Create a seed equipment claim while enforcing complete provenance."""

    return Equipment(
        id=id,
        equipment_type=equipment_type,
        equipment_name=name,
        brand_or_model=model,
        bed_width_in=width,
        bed_length_in=length,
        passes_48x48=bool(width and length and min(width, length) >= 48),
        materials=materials or [],
        file_formats=formats or [],
        requires_training=training,
        staff_assisted=staff_assisted,
        self_service=self_service,
        reservation_required=None,
        evidence_text=evidence,
        source_url=source,
        source_type="official_website",
        fetched_at=FETCHED_AT,
        confidence=confidence,
    )


PLACES = [
    Place(
        id="ucd-design-makerspace",
        name="UC Davis Design Makerspace",
        category="university_makerspace",
        description="Design fabrication labs in Cruess Hall with wood, metal, laser, 3D printing, and electronics equipment.",
        address="Cruess Hall, One Shields Avenue",
        city="Davis",
        state="CA",
        postal_code="95616",
        lat=38.5388,
        lng=-121.7489,
        website_url="https://designmakerspace.ucdavis.edu/",
        access_type="university",
        access_notes="University design facilities; confirm course, training, and project eligibility before visiting.",
        hours_text="Hours vary by lab and academic schedule.",
        qualification_status="verified_cnc_capable",
        confidence_score=98,
        last_checked_at=FETCHED_AT,
        staff_assisted=None,
        public_access=False,
        student_only=True,
        member_only=False,
        equipment=[
            equipment(
                id="ucd-cnc",
                equipment_type="cnc_router",
                name="CNC table",
                model="Laguna Smartshop II",
                width=48,
                length=96,
                evidence="CNC table (4'x8\"): Laguna Smartshop II",
                source="https://designmakerspace.ucdavis.edu/woodshop.html",
                confidence=0.99,
                materials=["wood", "plywood", "sheet goods"],
                training=True,
            ),
            equipment(
                id="ucd-laser",
                equipment_type="laser_cutter",
                name="Universal Laser Cutter ILS 12.75",
                model="Universal ILS 12.75",
                width=24,
                length=48,
                evidence="Universal Laser Cutter ILS 12.75 (24\"x 48\")",
                source="https://designmakerspace.ucdavis.edu/equipment.html",
                confidence=0.98,
                formats=["AI"],
                training=True,
            ),
            equipment(
                id="ucd-3d",
                equipment_type="3d_printer",
                name="3D printers",
                model="Ultimaker 2+ family",
                evidence="3D printers: Ultimaker 2+Connect, Ultimaker 2+, Ultimaker 2+ extended",
                source="https://designmakerspace.ucdavis.edu/equipment.html",
                confidence=0.98,
                formats=["STL"],
                training=True,
            ),
            equipment(
                id="ucd-woodshop",
                equipment_type="woodshop",
                name="Woodshop",
                evidence="The official equipment page lists a SawStop, CNC table, sanders, miter saw, routers, bandsaw, and panel saw.",
                source="https://designmakerspace.ucdavis.edu/equipment.html",
                confidence=0.98,
                materials=["wood", "plywood"],
                training=True,
            ),
        ],
    ),
    Place(
        id="scc-makerspace",
        name="Sacramento City College Makerspace",
        category="university_makerspace",
        description="A fabrication and prototyping space with large-format CNC, laser, 3D printing, textiles, and electronics.",
        address="3835 Freeport Boulevard",
        city="Sacramento",
        state="CA",
        postal_code="95822",
        lat=38.5419,
        lng=-121.4854,
        website_url="https://scc.losrios.edu/student-resources/makerspace",
        email="makerspace@scc.losrios.edu",
        access_type="students_faculty_staff",
        access_notes="Free and open to currently enrolled SCC students, faculty, and staff.",
        hours_text="Spring: Monday 10–4; Tuesday–Thursday 10–7.",
        qualification_status="verified_cnc_capable",
        confidence_score=97,
        last_checked_at=FETCHED_AT,
        staff_assisted=True,
        public_access=False,
        student_only=True,
        member_only=False,
        equipment=[
            equipment(
                id="scc-cnc",
                equipment_type="cnc_router",
                name="CNC Router",
                width=48,
                length=96,
                evidence="The Fabrication and Prototyping Space equipment includes a 4’ x 8’ CNC Router.",
                source="https://scc.losrios.edu/student-resources/makerspace",
                confidence=0.99,
                materials=["wood", "sheet goods"],
                formats=["3D file formats"],
                training=True,
                staff_assisted=True,
            ),
            equipment(
                id="scc-laser",
                equipment_type="laser_cutter",
                name="Universal Systems Laser Cutter",
                evidence="The Fabrication and Prototyping Space equipment includes a Universal Systems Laser Cutter.",
                source="https://scc.losrios.edu/student-resources/makerspace",
                confidence=0.98,
                materials=["wood", "acrylic", "card stock", "fabric", "paper"],
                formats=["PDF", "DXF", "SVG"],
                training=True,
                staff_assisted=True,
            ),
            equipment(
                id="scc-vacuum",
                equipment_type="vacuum_former",
                name="Vacuum Former",
                evidence="The official SCC equipment list includes a Vacuum Former.",
                source="https://scc.losrios.edu/student-resources/makerspace",
                confidence=0.98,
                training=True,
                staff_assisted=True,
            ),
            equipment(
                id="scc-3d",
                equipment_type="3d_printer",
                name="3D printers",
                evidence="The Flex Space equipment list includes a Formlabs Form 2 SLA printer and eight 3D printers.",
                source="https://scc.losrios.edu/student-resources/makerspace",
                confidence=0.98,
                formats=["STL"],
                training=True,
            ),
            equipment(
                id="scc-electronics",
                equipment_type="electronics",
                name="Electronics and soldering tools",
                evidence="The Flex Space equipment list includes electronics, soldering guns, and Arduinos.",
                source="https://scc.losrios.edu/student-resources/makerspace",
                confidence=0.98,
                training=True,
            ),
        ],
    ),
    Place(
        id="yololab",
        name="Yolo County Library yololab",
        category="library_makerspace",
        description="A public-library makerspace for guided and independent learning, workshops, and repair cafés.",
        address="315 E. 14th Street",
        city="Davis",
        state="CA",
        postal_code="95616",
        lat=38.5566,
        lng=-121.7388,
        website_url="https://yolocountylibrary.org/yololab/",
        access_type="library_card",
        access_notes="Requires an active Yolo County Library card and completed registration packet.",
        hours_text="Monday 6–8; Tuesday 6–8; Thursday 9:30–11:30; Friday 3–5.",
        qualification_status="possible_match_needs_verification",
        confidence_score=63,
        last_checked_at=FETCHED_AT,
        staff_assisted=True,
        public_access=True,
        student_only=False,
        member_only=True,
        equipment=[
            equipment(
                id="yolo-3d",
                equipment_type="3d_printer",
                name="3D Printers",
                evidence="The official yololab equipment list links to 3D Printers.",
                source="https://yolocountylibrary.org/yololab/",
                confidence=0.95,
                training=True,
                self_service=True,
            ),
            equipment(
                id="yolo-vinyl",
                equipment_type="vinyl_cutter",
                name="Cricut",
                evidence="The official yololab equipment list links to Cricut equipment.",
                source="https://yolocountylibrary.org/yololab/",
                confidence=0.95,
                training=True,
                self_service=True,
            ),
        ],
    ),
    Place(
        id="ucd-prototyping-lab",
        name="UC Davis Prototyping Lab",
        category="university_makerspace",
        description="A design-student lab for laser cutting, 3D printing, and electronics coursework.",
        address="Cruess Hall, Room 1102, One Shields Avenue",
        city="Davis",
        state="CA",
        postal_code="95616",
        lat=38.5387,
        lng=-121.7487,
        website_url="https://arts.ucdavis.edu/prototyping-lab",
        phone="(530) 752-0105",
        email="mlrojasvaldez@ucdavis.edu",
        access_type="design_students",
        access_notes="Reserved for design classes and coursework; required training must be completed first.",
        hours_text="M/W/F 9–5; T/Th 9–7, subject to the academic schedule.",
        qualification_status="strong_match",
        confidence_score=88,
        last_checked_at=FETCHED_AT,
        staff_assisted=True,
        public_access=False,
        student_only=True,
        member_only=False,
        equipment=[
            equipment(
                id="proto-laser",
                equipment_type="laser_cutter",
                name="Universal Laser Cutters",
                width=24,
                length=48,
                evidence="Laser Cutters: Universal (32” × 18”) and (48” × 24”).",
                source="https://arts.ucdavis.edu/prototyping-lab",
                confidence=0.99,
                formats=["AI"],
                training=True,
            ),
            equipment(
                id="proto-3d",
                equipment_type="3d_printer",
                name="3D printers",
                model="Ultimaker 2+ Connect and Bambu Lab X1 Carbon",
                evidence="3D printers: Ultimaker 2+ Connect | Bambu Lab X1 Carbon.",
                source="https://arts.ucdavis.edu/prototyping-lab",
                confidence=0.99,
                formats=["STL"],
                training=True,
            ),
            equipment(
                id="proto-electronics",
                equipment_type="electronics",
                name="Soldering iron",
                evidence="The official equipment list includes a soldering iron.",
                source="https://arts.ucdavis.edu/prototyping-lab",
                confidence=0.98,
                training=True,
            ),
        ],
    ),
    Place(
        id="ucd-tech-foundry",
        name="UC Davis Tech Foundry",
        category="commercial_fabrication_shop",
        description="A university device-development facility that designs and manufactures research and prototype devices.",
        address="451 Health Sciences Drive",
        city="Davis",
        state="CA",
        postal_code="95616",
        lat=38.5344,
        lng=-121.7647,
        website_url="https://bme.ucdavis.edu/about/tech-foundry",
        access_type="service",
        access_notes="Supports UC Davis faculty, private companies, and individuals through a service model.",
        hours_text="Contact the Tech Foundry for project intake and scheduling.",
        qualification_status="strong_match",
        confidence_score=82,
        last_checked_at=FETCHED_AT,
        staff_assisted=True,
        public_access=True,
        student_only=False,
        member_only=False,
        equipment=[
            equipment(
                id="foundry-cnc",
                equipment_type="cnc_mill",
                name="Computer numerical control mills",
                evidence="The Aggie Square facility features modern 3D printers and computer numerical control mills.",
                source="https://bme.ucdavis.edu/about/tech-foundry",
                confidence=0.96,
                staff_assisted=True,
            ),
            equipment(
                id="foundry-3d",
                equipment_type="3d_printer",
                name="Modern 3D printers",
                evidence="The Aggie Square facility features modern 3D printers and computer numerical control mills.",
                source="https://bme.ucdavis.edu/about/tech-foundry",
                confidence=0.96,
                staff_assisted=True,
            ),
        ],
    ),
    Place(
        id="sac-state-stingerstudio",
        name="Sac State StingerStudio Makerspace",
        category="university_makerspace",
        description="A university-library makerspace with CNC, 3D printing, laser/vinyl cutting, sewing, and electronics.",
        address="2000 State University Drive",
        city="Sacramento",
        state="CA",
        postal_code="95819",
        lat=38.5592,
        lng=-121.4235,
        website_url="https://library.csus.edu/makerspace",
        access_type="university",
        access_notes="Software and support information is directed to the Sacramento State community; verify visitor access.",
        hours_text="See the current library makerspace schedule.",
        qualification_status="possible_match_needs_verification",
        confidence_score=72,
        last_checked_at=FETCHED_AT,
        staff_assisted=True,
        public_access=None,
        student_only=True,
        member_only=False,
        equipment=[
            equipment(
                id="stinger-cnc",
                equipment_type="cnc_router",
                name="CNC Router",
                evidence="The official equipment page says its CNC machine can create signs, plaques, topology maps, and complex shapes.",
                source="https://library.csus.edu/makerspace",
                confidence=0.96,
                training=True,
                staff_assisted=True,
            ),
            equipment(
                id="stinger-laser",
                equipment_type="laser_cutter",
                name="Laser Cutter",
                evidence="The official page says its laser cutter can etch designs or cut shapes from a range of materials.",
                source="https://library.csus.edu/makerspace",
                confidence=0.96,
                training=True,
            ),
            equipment(
                id="stinger-3d",
                equipment_type="3d_printer",
                name="3D Printers",
                evidence="The official equipment page lists 3D printers that construct objects from a digital model.",
                source="https://library.csus.edu/makerspace",
                confidence=0.96,
                formats=["3D model"],
            ),
            equipment(
                id="stinger-sewing",
                equipment_type="sewing",
                name="Sewing and embroidery machines",
                evidence="The official page lists manual sewing machines and programmable digital embroidery devices.",
                source="https://library.csus.edu/makerspace",
                confidence=0.96,
            ),
        ],
    ),
]


def get_place(place_id: str) -> Place | None:
    return next((place for place in PLACES if place.id == place_id), None)

